name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.
        with:
          php-version: 7.4
      - run: php --version
